-- ============================================================================
-- APBS database schema — RECONSTRUCTED from backend/server.js queries
-- ============================================================================
-- There was no schema dump in the repo, so this file was generated by
-- extracting every table/column referenced in the backend's SQL queries.
-- Column types are inferred from usage. Treat it as a working starting
-- point: if a screen throws "Unknown column" errors, that column needs to
-- be added/adjusted here.
--
-- Import into an existing empty database named `apbs_db`:
--   mysql -u root -p apbs_db < apbs_db_schema.sql
--
-- Default login seeded at the bottom:  username: admin   password: admin123
-- ============================================================================

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Accounts / auth
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  employee_id INT NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  position VARCHAR(100) NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_history (
  login_history_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NULL,
  date DATETIME NULL,
  role VARCHAR(50) NULL,
  action VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_trail (
  audit_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  date DATETIME NULL,
  role VARCHAR(50) NULL,
  action VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Employee master data + lookups
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS emp_info (
  emp_id INT AUTO_INCREMENT PRIMARY KEY,
  l_name VARCHAR(100) NULL,
  f_name VARCHAR(100) NULL,
  m_name VARCHAR(100) NULL,
  suffix VARCHAR(20) NULL,
  civil_status VARCHAR(50) NULL,
  sex VARCHAR(20) NULL,
  citizenship VARCHAR(100) NULL,
  religion VARCHAR(100) NULL,
  birthday DATE NULL,
  province_of_birth VARCHAR(100) NULL,
  city_of_birth VARCHAR(100) NULL,
  email VARCHAR(150) NULL,
  mobile_num VARCHAR(30) NULL,
  region VARCHAR(100) NULL,
  province VARCHAR(100) NULL,
  city VARCHAR(100) NULL,
  barangay VARCHAR(100) NULL,
  street VARCHAR(150) NULL,
  street_add VARCHAR(150) NULL,
  emp_status VARCHAR(50) NULL,
  emp_type VARCHAR(50) NULL,
  emp_emptype VARCHAR(50) NULL,
  position VARCHAR(100) NULL,
  emp_pos VARCHAR(100) NULL,
  rate_type VARCHAR(50) NULL,
  emp_ratetype VARCHAR(50) NULL,
  salary_rate DECIMAL(12,2) NULL,
  emp_rate DECIMAL(12,2) NULL,
  department VARCHAR(100) NULL,
  emp_dept VARCHAR(100) NULL,
  date_hired DATE NULL,
  emp_datehired DATE NULL,
  date_end DATE NULL,
  emp_dateend DATE NULL,
  tin_num VARCHAR(30) NULL,
  sss_num VARCHAR(30) NULL,
  philhealth_num VARCHAR(30) NULL,
  hdmf_num VARCHAR(30) NULL,
  emp_days_work_per_year INT NULL DEFAULT 261,
  image VARCHAR(255) NULL,
  rfid VARCHAR(100) NULL,
  is_archive TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_info_try (
  emp_id INT AUTO_INCREMENT PRIMARY KEY,
  f_name VARCHAR(100) NULL,
  m_name VARCHAR(100) NULL,
  l_name VARCHAR(100) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS civil_status (
  cs_id INT AUTO_INCREMENT PRIMARY KEY,
  cs_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sex (
  sex_id INT AUTO_INCREMENT PRIMARY KEY,
  sex_name VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS religion (
  religion_id INT AUTO_INCREMENT PRIMARY KEY,
  religion_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS countries (
  country_id INT AUTO_INCREMENT PRIMARY KEY,
  country_name VARCHAR(100) NULL,
  nationality VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_status (
  emp_status_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_status_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employment_type (
  employment_type_id INT AUTO_INCREMENT PRIMARY KEY,
  employment_type_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_department (
  dept_id INT AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rate_type (
  rt_id INT AUTO_INCREMENT PRIMARY KEY,
  rt_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rate_type_value (
  rtv_id INT AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(100) NULL,
  value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rate_value (
  position_id INT AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(100) NOT NULL,
  value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_report_category (
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS education_background (
  educ_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  school_id INT NULL,
  school_uni_id INT NULL,
  school_university VARCHAR(200) NULL,
  category VARCHAR(100) NULL,
  year VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_education_background (
  educ_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  school_id INT NULL,
  school_university VARCHAR(200) NULL,
  category VARCHAR(100) NULL,
  year VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_work_exp (
  work_exp_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  category_id INT NULL,
  company_name VARCHAR(200) NULL,
  position VARCHAR(100) NULL,
  year VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Attendance
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS emp_attendance (
  emp_attendance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  date DATE NULL,
  time_in TIME NULL,
  break_in TIME NULL,
  break_out TIME NULL,
  time_out TIME NULL,
  entry_status VARCHAR(30) NULL,
  time_out_status VARCHAR(30) NULL,
  day_status VARCHAR(50) NULL,
  total_break_hours DECIMAL(8,2) NULL,
  total_hours DECIMAL(8,2) NULL,
  total_ot_hours DECIMAL(8,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_attendance_1 (
  attendance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  time_in DATETIME NULL,
  time_out DATETIME NULL,
  attendance_status VARCHAR(30) NULL,
  entry_status VARCHAR(30) NULL,
  rate_table_id INT NULL,
  total_hours DECIMAL(8,2) NULL,
  total_hours_worked DECIMAL(8,2) NULL,
  total_regular_hours DECIMAL(8,2) NULL,
  total_ot_hours DECIMAL(8,2) NULL,
  total_regular_ot_hours DECIMAL(8,2) NULL,
  total_night_diff_hours DECIMAL(8,2) NULL,
  total_night_diff_ot_hours DECIMAL(8,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_attendance_1_1 (
  attendance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  time_in DATETIME NULL,
  time_out DATETIME NULL,
  attendance_status VARCHAR(30) NULL,
  entry_status VARCHAR(30) NULL,
  rate_table_id INT NULL,
  total_hours DECIMAL(8,2) NULL,
  total_hours_worked DECIMAL(8,2) NULL,
  total_regular_hours DECIMAL(8,2) NULL,
  total_ot_hours DECIMAL(8,2) NULL,
  total_regular_ot_hours DECIMAL(8,2) NULL,
  total_night_diff_hours DECIMAL(8,2) NULL,
  total_night_diff_ot_hours DECIMAL(8,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_attendance_2 (
  attendance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  date DATE NULL,
  time_in TIME NULL,
  break_in TIME NULL,
  break_out TIME NULL,
  time_out TIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_atten_timeallow (
  timeallow_id INT AUTO_INCREMENT PRIMARY KEY,
  timeallow_name VARCHAR(100) NULL,
  percentage_deduction DECIMAL(8,2) NULL,
  status VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS absent_present_count (
  id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  absent_count INT NULL DEFAULT 0,
  present_count INT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Leave
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS emp_leave_type (
  emp_leave_type_id INT AUTO_INCREMENT PRIMARY KEY,
  leave_type_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_leave (
  emp_leave_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  leave_type_id INT NULL,
  leave_type_name VARCHAR(100) NULL,
  date_start DATE NULL,
  date_end DATE NULL,
  leave_use DECIMAL(6,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_leave_balance (
  leave_balance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  leave_type_id INT NULL,
  leave_type_name VARCHAR(100) NULL,
  leave_balance DECIMAL(6,2) NULL,
  leave_spent DECIMAL(6,2) NULL,
  leave_remaining DECIMAL(6,2) NULL,
  date_start DATE NULL,
  date_end DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Allowances / benefits / de minimis
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS allowance_benefits (
  allowance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  allowance_name VARCHAR(100) NULL,
  allowance_value DECIMAL(12,2) NULL,
  allowance_type VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_allowance_benefits (
  allowance_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  allowance_name VARCHAR(100) NULL,
  allowance_value DECIMAL(12,2) NULL,
  allowance_type VARCHAR(50) NULL,
  status VARCHAR(30) NULL DEFAULT 'Active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_allowance_benefits_deminimis_monthly (
  deminimis_monthly_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  rice_allow DECIMAL(12,2) NULL,
  clothing_allow DECIMAL(12,2) NULL,
  laundry_allow DECIMAL(12,2) NULL,
  medical_allow DECIMAL(12,2) NULL,
  allowance_type VARCHAR(50) NULL,
  status VARCHAR(30) NULL DEFAULT 'Active',
  date_activate DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_allowance_benefits_deminimis_annually (
  deminimis_annual_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  actualmedical_assist DECIMAL(12,2) NULL,
  achivement_allow DECIMAL(12,2) NULL,
  status VARCHAR(30) NULL DEFAULT 'Active',
  date_activate DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- De minimis non-taxable ceilings used by payroll computation
CREATE TABLE IF NOT EXISTS emp_deminimis (
  deminimis_id INT AUTO_INCREMENT PRIMARY KEY,
  allowance_type VARCHAR(50) NULL,
  rice_allow DECIMAL(12,2) NULL,
  clothing_allow DECIMAL(12,2) NULL,
  laundry_allow DECIMAL(12,2) NULL,
  medical_allow DECIMAL(12,2) NULL,
  actualmedical_assist DECIMAL(12,2) NULL,
  achivement_allow DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Loans
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS loan_type (
  loan_type_id INT AUTO_INCREMENT PRIMARY KEY,
  loan_type_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS company_loan_name (
  company_loan_id INT AUTO_INCREMENT PRIMARY KEY,
  company_loan_name VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS company_loan_type (
  company_loan_type_id INT AUTO_INCREMENT PRIMARY KEY,
  company_loan_type_name VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_goverment (
  government_id INT AUTO_INCREMENT PRIMARY KEY,
  government_name VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_loan_type (
  emp_loan_type_id INT AUTO_INCREMENT PRIMARY KEY,
  goverment_name VARCHAR(150) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_status_loans (
  emp_status_loans_id INT AUTO_INCREMENT PRIMARY KEY,
  status_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_company_loans (
  emp_company_loans_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  loan_name VARCHAR(150) NULL,
  loan_type VARCHAR(150) NULL,
  loan_amount DECIMAL(12,2) NULL,
  loan_monthly_payment DECIMAL(12,2) NULL,
  payment_terms VARCHAR(50) NULL,
  loan_interest_per_month DECIMAL(8,2) NULL,
  penalty DECIMAL(12,2) NULL,
  penalty_option VARCHAR(50) NULL,
  total_loan DECIMAL(12,2) NULL,
  total_payments_previous_employer DECIMAL(12,2) NULL,
  period_of_deduction VARCHAR(50) NULL,
  beginning_balance DECIMAL(12,2) NULL,
  status VARCHAR(30) NULL,
  startDate DATE NULL,
  endDate DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_goverment_loans (
  emp_goverment_loans_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  government_id INT NULL,
  government_name VARCHAR(150) NULL,
  loan_type_id INT NULL,
  loan_type_name VARCHAR(150) NULL,
  loan_amount DECIMAL(12,2) NULL,
  loan_interest_per_month DECIMAL(8,2) NULL,
  loan_monthly_payment DECIMAL(12,2) NULL,
  penalty DECIMAL(12,2) NULL,
  penalty_option VARCHAR(50) NULL,
  total_loan DECIMAL(12,2) NULL,
  total_payments_previous_employer DECIMAL(12,2) NULL,
  period_of_deduction VARCHAR(50) NULL,
  beginning_balance DECIMAL(12,2) NULL,
  status VARCHAR(30) NULL,
  startDate DATE NULL,
  endDate DATE NULL,
  payment_terms VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_loans (
  emp_loans_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_loans_date DATE NULL,
  emp_date_coverage VARCHAR(100) NULL,
  emp_loans_payroll_type VARCHAR(50) NULL,
  emp_loans_payroll_cycle VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_loan_summary (
  loan_summary_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  loan_ID INT NULL,
  emp_loans_date DATE NULL,
  payroll_cycle VARCHAR(50) NULL,
  loan_amount DECIMAL(12,2) NULL,
  penalty DECIMAL(12,2) NULL,
  penalty_option VARCHAR(50) NULL,
  loan_type_name VARCHAR(150) NULL,
  payment_terms VARCHAR(50) NULL,
  total_loan DECIMAL(12,2) NULL,
  total_loan_remaining DECIMAL(12,2) NULL,
  loan_source VARCHAR(100) NULL,
  emp_date_coverage VARCHAR(100) NULL,
  emp_loans_payroll_type VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Payroll settings / brackets
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS settings_category (
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings_payroll (
  paysett_id INT AUTO_INCREMENT PRIMARY KEY,
  paysett_name VARCHAR(100) NOT NULL,
  paysett_label VARCHAR(150) NULL,
  paysett_value VARCHAR(10) NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings_payroll_2 (
  paysett2_id INT AUTO_INCREMENT PRIMARY KEY,
  paysett2_name VARCHAR(100) NOT NULL,
  paysett2_startdate VARCHAR(20) NULL,
  paysett2_enddate VARCHAR(20) NULL,
  paysett2_value VARCHAR(50) NULL,
  paysett2_release VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payroll_type (
  payroll_type_id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_type_name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payroll_cycles (
  payroll_cycle_id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_type VARCHAR(50) NULL,
  cycle_type VARCHAR(50) NULL,
  start_day INT NULL,
  end_day INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_date_cycle (
  date_cycle_id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_type VARCHAR(50) NULL,
  cycle_type VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Hour-rate multipliers per day type (rt1..rt10 in payroll computation)
CREATE TABLE IF NOT EXISTS rate_table (
  rate_table_id INT AUTO_INCREMENT PRIMARY KEY,
  rate_table_name VARCHAR(100) NULL,
  regular_shift DECIMAL(8,4) NULL,
  overtime_shift DECIMAL(8,4) NULL,
  regular_shift_nsd DECIMAL(8,4) NULL,
  overtime_shift_nsd DECIMAL(8,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sss_bracket (
  sss_id INT AUTO_INCREMENT PRIMARY KEY,
  sss_min DECIMAL(12,2) NULL,
  sss_max DECIMAL(12,2) NULL,
  ee_share DECIMAL(12,2) NULL,
  er_share DECIMAL(12,2) NULL,
  ec DECIMAL(12,2) NULL,
  wisp_ee DECIMAL(12,2) NULL,
  wisp_er DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS philhealth_bracket (
  phb_id INT AUTO_INCREMENT PRIMARY KEY,
  phb_min_philhealth DECIMAL(12,2) NULL,
  phb_max_philhealth DECIMAL(12,2) NULL,
  phb_value DECIMAL(8,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hdmf_bracket (
  hdmf_id INT AUTO_INCREMENT PRIMARY KEY,
  hdmf_min DECIMAL(12,2) NULL,
  hdmf_max DECIMAL(12,2) NULL,
  hdmf_value_ee DECIMAL(8,4) NULL,
  hdmf_value_er DECIMAL(8,4) NULL,
  `limit` DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tax_brackets_monthly (
  tax_bracket_id INT AUTO_INCREMENT PRIMARY KEY,
  min_income DECIMAL(12,2) NULL,
  max_income DECIMAL(12,2) NULL,
  fixed_tax DECIMAL(12,2) NULL,
  percentage_deduction_tax DECIMAL(8,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tax_brackets_semi_monthly (
  tax_bracket_id INT AUTO_INCREMENT PRIMARY KEY,
  min_income DECIMAL(12,2) NULL,
  max_income DECIMAL(12,2) NULL,
  fixed_tax DECIMAL(12,2) NULL,
  percentage_deduction_tax DECIMAL(8,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- System variables (managed in the System Variable screen)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sys_tax (
  tax_id INT AUTO_INCREMENT PRIMARY KEY,
  tax_name VARCHAR(100) NULL,
  tax_value DECIMAL(12,4) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_dmb (
  dmb_id INT AUTO_INCREMENT PRIMARY KEY,
  dmb_name VARCHAR(100) NOT NULL,
  dmb_value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_deduc (
  deduc_id INT AUTO_INCREMENT PRIMARY KEY,
  deduc_name VARCHAR(100) NOT NULL,
  deduc_value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_nprtrv (
  nprtrv_id INT AUTO_INCREMENT PRIMARY KEY,
  nprtrv_name VARCHAR(100) NOT NULL,
  nprtrv_value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Earnings / deductions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS earn_deduct (
  earn_deduct_id INT AUTO_INCREMENT PRIMARY KEY,
  earn_deduct_name VARCHAR(150) NULL,
  earning_or_deduction VARCHAR(30) NULL,
  amount DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_pay_des (
  pay_des_id INT AUTO_INCREMENT PRIMARY KEY,
  pay_description VARCHAR(150) NOT NULL,
  earning_or_deduction VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_onetime_earn_deduct (
  emp_onetime_earn_deduct_id INT AUTO_INCREMENT PRIMARY KEY,
  year VARCHAR(10) NULL,
  month VARCHAR(20) NULL,
  payroll_type VARCHAR(50) NULL,
  cycle_type VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_onetime_earn_deduct_per_emp (
  emp_onetime_earn_deduct_per_emp_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_onetime_earn_deduct_id INT NULL,
  year VARCHAR(10) NULL,
  month VARCHAR(20) NULL,
  cycle_type VARCHAR(50) NULL,
  payroll_type VARCHAR(50) NULL,
  emp_id INT NULL,
  emp_fullname VARCHAR(200) NULL,
  earning_or_deduction VARCHAR(30) NULL,
  pay_description VARCHAR(150) NULL,
  amount DECIMAL(12,2) NULL,
  remarks VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Payroll runs
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS emp_payroll (
  payroll_id INT AUTO_INCREMENT PRIMARY KEY,
  startDate DATE NULL,
  endDate DATE NULL,
  payrollType VARCHAR(50) NULL,
  payrollCycle VARCHAR(50) NULL,
  payroll_date DATE NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_payroll_part_1 (
  payroll_part_1_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  full_name VARCHAR(200) NULL,
  payrollType VARCHAR(50) NULL,
  payrollCycle VARCHAR(50) NULL,
  startDate DATE NULL,
  endDate DATE NULL,
  emp_rate DECIMAL(12,2) NULL,
  hourly_rate DECIMAL(12,2) NULL,
  emp_ratetype VARCHAR(50) NULL,
  emp_pos VARCHAR(100) NULL,
  total_late_count DECIMAL(8,2) NULL,
  total_late_value DECIMAL(12,2) NULL,
  total_absent_count DECIMAL(8,2) NULL,
  total_absent_value DECIMAL(12,2) NULL,
  total_hours_ DECIMAL(10,2) NULL,
  total_hours_work DECIMAL(10,2) NULL,
  total_reg_hours_rt1_r DECIMAL(10,2) NULL,
  total_regular_hours_value_rt1 DECIMAL(12,2) NULL,
  total_reg_hours_rt2_rd DECIMAL(10,2) NULL,
  total_regular_hours_value_rt2 DECIMAL(12,2) NULL,
  total_reg_hours_rt3_sh DECIMAL(10,2) NULL,
  total_regular_hours_value_rt3 DECIMAL(12,2) NULL,
  total_reg_hours_rt4_shrd DECIMAL(10,2) NULL,
  total_regular_hours_value_rt4 DECIMAL(12,2) NULL,
  total_reg_hours_rt5_dsh DECIMAL(10,2) NULL,
  total_regular_hours_value_rt5 DECIMAL(12,2) NULL,
  total_reg_hours_rt6_dshrd DECIMAL(10,2) NULL,
  total_regular_hours_value_rt6 DECIMAL(12,2) NULL,
  total_reg_hours_rt7_rh DECIMAL(10,2) NULL,
  total_regular_hours_value_rt7 DECIMAL(12,2) NULL,
  total_reg_hours_rt8_rhrd DECIMAL(10,2) NULL,
  total_regular_hours_value_rt8 DECIMAL(12,2) NULL,
  total_reg_hours_rt9_drh DECIMAL(10,2) NULL,
  total_regular_hours_value_rt9 DECIMAL(12,2) NULL,
  total_reg_hours_rt10_drhrd DECIMAL(10,2) NULL,
  total_regular_hours_value_rt10 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt1_r DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt1 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt2_rd DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt2 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt3_sh DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt3 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt4_shrd DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt4 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt5_dsh DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt5 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt6_dshrd DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt6 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt7_rh DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt7 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt8_rhrd DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt8 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt9_drh DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt9 DECIMAL(12,2) NULL,
  overtime_regular_hours_rt10_drhrd DECIMAL(10,2) NULL,
  total_overtime_hours_value_rt10 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt1_r DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt1 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt2_rd DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt2 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt3_sh DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt3 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt4_shrd DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt4 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt5_dsh DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt5 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt6_dshrd DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt6 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt7_rh DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt7 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt8_rhrd DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt8 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt9_drh DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt9 DECIMAL(12,2) NULL,
  total_nightdiff_hours_rt10_drhrd DECIMAL(10,2) NULL,
  total_nightdiff_hours_value_rt10 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt1_r DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt1 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt2_rd DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt2 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt3_sh DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt3 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt4_shrd DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt4 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt5_dsh DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt5 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt6_dshrd DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt6 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt7_rh DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt7 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt8_rhrd DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt8 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt9_drh DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt9 DECIMAL(12,2) NULL,
  overtime_nightdiff_hours_rt10_drhrd DECIMAL(10,2) NULL,
  total_overtime_nightdiff_hours_value_rt10 DECIMAL(12,2) NULL,
  total_overtime_hours_rt1_r DECIMAL(10,2) NULL,
  total_overtime_hours_rt2_rd DECIMAL(10,2) NULL,
  total_overtime_hours_rt3_sh DECIMAL(10,2) NULL,
  total_overtime_hours_rt4_shrd DECIMAL(10,2) NULL,
  total_overtime_hours_rt5_dsh DECIMAL(10,2) NULL,
  total_overtime_hours_rt6_dshrd DECIMAL(10,2) NULL,
  total_overtime_hours_rt7_rh DECIMAL(10,2) NULL,
  total_overtime_hours_rt8_rhrd DECIMAL(10,2) NULL,
  total_overtime_hours_rt9_drh DECIMAL(10,2) NULL,
  total_overtime_hours_rt10_drhrd DECIMAL(10,2) NULL,
  total_regular_hours_value DECIMAL(12,2) NULL,
  total_overtime_hours_value DECIMAL(12,2) NULL,
  total_nightdiff_hours_value DECIMAL(12,2) NULL,
  total_overtime_nightdiff_hours_value DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_payroll_part_2 (
  payroll_part_2_id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NULL,
  full_name VARCHAR(200) NULL,
  payrollType VARCHAR(50) NULL,
  payrollCycle VARCHAR(50) NULL,
  totalDays DECIMAL(8,2) NULL,
  startDate DATE NULL,
  endDate DATE NULL,
  emp_rate DECIMAL(12,2) NULL,
  emp_pos VARCHAR(100) NULL,
  total_late_value DECIMAL(12,2) NULL,
  total_absent_value DECIMAL(12,2) NULL,
  rice_allow DECIMAL(12,2) NULL,
  clothing_allow DECIMAL(12,2) NULL,
  laundry_allow DECIMAL(12,2) NULL,
  medical_allow DECIMAL(12,2) NULL,
  rice_allow_excess DECIMAL(12,2) NULL,
  clothing_allow_excess DECIMAL(12,2) NULL,
  laundry_allow_excess DECIMAL(12,2) NULL,
  medical_allow_excess DECIMAL(12,2) NULL,
  regular_value DECIMAL(12,2) NULL,
  total_regular_hours DECIMAL(10,2) NULL,
  total_regular_value DECIMAL(12,2) NULL,
  total_overtime_hours DECIMAL(10,2) NULL,
  total_overtime_value DECIMAL(12,2) NULL,
  total_nightdiff_hours DECIMAL(10,2) NULL,
  total_nightdiff_value DECIMAL(12,2) NULL,
  total_overtime_nightdiff_hours DECIMAL(10,2) NULL,
  total_overtime_nightdiff_value DECIMAL(12,2) NULL,
  total_hours_work DECIMAL(10,2) NULL,
  non_taxable_deminimis DECIMAL(12,2) NULL,
  total_deminimis_allowance DECIMAL(12,2) NULL,
  total_allow_excess DECIMAL(12,2) NULL,
  total_allow_benefits_m DECIMAL(12,2) NULL,
  total_worked_value DECIMAL(12,2) NULL,
  total_taxable_income DECIMAL(12,2) NULL,
  total_gross_income DECIMAL(12,2) NULL,
  Excess_tax DECIMAL(12,2) NULL,
  percentage_deduction_tax DECIMAL(8,4) NULL,
  total_percentage_tax DECIMAL(12,2) NULL,
  total_fixed_tax DECIMAL(12,2) NULL,
  total_tax DECIMAL(12,2) NULL,
  total_value_after_tax DECIMAL(12,2) NULL,
  employee_sss_share DECIMAL(12,2) NULL,
  employer_sss_share DECIMAL(12,2) NULL,
  employment_compensation_share DECIMAL(12,2) NULL,
  wisp_employee_share DECIMAL(12,2) NULL,
  wisp_employer_share DECIMAL(12,2) NULL,
  total_philhealth DECIMAL(12,2) NULL,
  employee_philhealth DECIMAL(12,2) NULL,
  employer_philhealth DECIMAL(12,2) NULL,
  employee_hdmf DECIMAL(12,2) NULL,
  employer_hdmf DECIMAL(12,2) NULL,
  total_contribution_deduction DECIMAL(12,2) NULL,
  total_gov_deduction DECIMAL(12,2) NULL,
  total_loan_amount DECIMAL(12,2) NULL,
  total_deduction DECIMAL(12,2) NULL,
  total_net_pay DECIMAL(12,2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Reports
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS emp_report (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  date DATETIME NULL,
  details TEXT NULL,
  emp_id INT NULL,
  emp_name VARCHAR(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emp_report_1 (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  date DATETIME NULL,
  details TEXT NULL,
  emp_id INT NULL,
  emp_name VARCHAR(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payroll_report (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  date DATETIME NULL,
  details TEXT NULL,
  emp_id INT NULL,
  emp_name VARCHAR(200) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- SEED DATA (minimum needed for the app to boot; edit to taste)
-- ============================================================================

-- Login: admin / admin123  (passwords are stored in plaintext by this app)
INSERT INTO users (emp_id, employee_id, first_name, last_name, position, username, password, role)
VALUES (1, 1, 'System', 'Administrator', 'Administrator', 'admin', 'admin123', 'Admin');

INSERT INTO sex (sex_name) VALUES ('Male'), ('Female');

INSERT INTO civil_status (cs_name) VALUES ('Single'), ('Married'), ('Widowed'), ('Separated');

INSERT INTO religion (religion_name) VALUES
('Roman Catholic'), ('Christian'), ('Iglesia ni Cristo'), ('Islam'), ('Buddhist'), ('Others');

INSERT INTO countries (country_name, nationality) VALUES
('Philippines', 'Filipino'), ('United States', 'American'), ('Japan', 'Japanese'),
('China', 'Chinese'), ('South Korea', 'Korean'), ('India', 'Indian');

INSERT INTO emp_status (emp_status_name) VALUES ('Active'), ('Resigned'), ('Terminated'), ('Retired');

INSERT INTO employment_type (employment_type_name) VALUES ('Regular'), ('Probationary'), ('Contractual'), ('Part-Time');

INSERT INTO emp_department (dept_name) VALUES ('Human Resources'), ('Accounting'), ('IT'), ('Operations');

INSERT INTO rate_type (rt_name) VALUES ('Monthly'), ('Daily'), ('Hourly');

INSERT INTO emp_report_category (category_name) VALUES
('Elementary'), ('High School'), ('Senior High School'), ('Vocational'), ('College'), ('Post-Graduate');

INSERT INTO emp_leave_type (leave_type_name) VALUES ('Sick Leave'), ('Vacation Leave'), ('Emergency Leave');

INSERT INTO emp_goverment (government_name) VALUES ('SSS'), ('Pag-IBIG (HDMF)'), ('GSIS');

INSERT INTO loan_type (loan_type_name) VALUES ('Salary Loan'), ('Calamity Loan'), ('Multi-Purpose Loan');

INSERT INTO emp_status_loans (status_name) VALUES ('Active'), ('Fully Paid'), ('On Hold');

INSERT INTO emp_pay_des (pay_description, earning_or_deduction) VALUES
('Bonus', 'Earning'), ('Salary Adjustment', 'Earning'), ('Cash Advance', 'Deduction');

INSERT INTO payroll_type (payroll_type_name) VALUES ('Monthly'), ('Semi-Monthly');

INSERT INTO payroll_cycles (payroll_type, cycle_type, start_day, end_day) VALUES
('Semi-Monthly', '1stCycle', 1, 15),
('Semi-Monthly', '2ndCycle', 16, 31),
('Monthly', 'Monthly', 1, 31);

-- Payroll toggle settings referenced by name throughout the payroll queries.
-- paysett_value: '1' = enabled, '0' = disabled.
INSERT INTO settings_payroll (paysett_name, paysett_label, paysett_value) VALUES
('Semi-Monthly', 'Semi-monthly payroll', '1'),
('Monthly', 'Monthly payroll', '0'),
('1stCycle', 'Deduct allowances on 1st cycle', '1'),
('2ndCycle', 'Deduct allowances on 2nd cycle', '1'),
('SSS', 'Deduct SSS on 2nd cycle (monthly basis)', '1'),
('SSS-Per-Cycle', 'Deduct SSS every cycle', '0'),
('Philhealth', 'Deduct PhilHealth on 2nd cycle (monthly basis)', '1'),
('Philhealth-Per-Cycle', 'Deduct PhilHealth every cycle', '0'),
('HDMF', 'Deduct Pag-IBIG on 2nd cycle (monthly basis)', '1'),
('HDMF-Per-Cycle', 'Deduct Pag-IBIG every cycle', '0'),
('Tax', 'Withhold tax monthly', '1'),
('Tax-Per-Cycle', 'Withhold tax every cycle', '0'),
('Regular-Holiday', 'Pay regular holidays', '1'),
('Regular-Holiday-on-Restday', 'Pay regular holiday on rest day', '1'),
('Special-Holiday', 'Pay special holidays', '1'),
('Special-Holiday-on-Restday', 'Pay special holiday on rest day', '1'),
('Double-Regular-Holiday', 'Pay double regular holidays', '1'),
('Double-Regular-Holiday-on-Restday', 'Pay double regular holiday on rest day', '1'),
('Double-Special-Holiday', 'Pay double special holidays', '1'),
('Double-Special-Holiday-on-Restday', 'Pay double special holiday on rest day', '1');

-- Day-type pay multipliers (PH labor-standard defaults; adjust to policy)
INSERT INTO rate_table (rate_table_name, regular_shift, overtime_shift, regular_shift_nsd, overtime_shift_nsd) VALUES
('Regular Day',                          1.00, 1.25, 1.10, 1.375),
('Rest Day',                             1.30, 1.69, 1.43, 1.859),
('Special Holiday',                      1.30, 1.69, 1.43, 1.859),
('Special Holiday on Rest Day',          1.50, 1.95, 1.65, 2.145),
('Double Special Holiday',               1.50, 1.95, 1.65, 2.145),
('Double Special Holiday on Rest Day',   1.95, 2.535, 2.145, 2.789),
('Regular Holiday',                      2.00, 2.60, 2.20, 2.86),
('Regular Holiday on Rest Day',          2.60, 3.38, 2.86, 3.718),
('Double Regular Holiday',               3.00, 3.90, 3.30, 4.29),
('Double Regular Holiday on Rest Day',   3.90, 5.07, 4.29, 5.577);

-- De minimis non-taxable ceilings (BIR defaults; adjust as needed)
INSERT INTO emp_deminimis (allowance_type, rice_allow, clothing_allow, laundry_allow, medical_allow, actualmedical_assist, achivement_allow)
VALUES ('Monthly', 2000.00, 500.00, 300.00, 250.00, 10000.00, 10000.00);

-- Late deduction rule (percentage of the hourly/daily rate deducted per late)
INSERT INTO emp_atten_timeallow (timeallow_name, percentage_deduction, status)
VALUES ('Late Deduction', 100.00, 'Active');

INSERT INTO sys_tax (tax_name, tax_value) VALUES ('Withholding Tax', 0);

-- PhilHealth premium (2024+: 5% of monthly basic, split EE/ER; floor 10k / ceiling 100k)
INSERT INTO philhealth_bracket (phb_min_philhealth, phb_max_philhealth, phb_value)
VALUES (10000.00, 100000.00, 0.05);

-- Pag-IBIG contribution rates (EE 1% below 1.5k, 2% at/above; fund salary cap 10k)
INSERT INTO hdmf_bracket (hdmf_min, hdmf_max, hdmf_value_ee, hdmf_value_er, `limit`) VALUES
(0.00, 1500.00, 0.01, 0.02, 10000.00),
(1500.01, NULL, 0.02, 0.02, 10000.00);

-- SSS 2025 contribution sample brackets (REPLACE with the full official table —
-- the real schedule has ~50 rows; these are representative rows so payroll runs)
INSERT INTO sss_bracket (sss_min, sss_max, ee_share, er_share, ec, wisp_ee, wisp_er) VALUES
(0.00,      5249.99,  250.00,  510.00, 10.00, 0.00, 0.00),
(5250.00,   9749.99,  375.00,  765.00, 10.00, 0.00, 0.00),
(9750.00,  14749.99,  600.00, 1230.00, 10.00, 0.00, 0.00),
(14750.00, 19749.99,  850.00, 1750.00, 10.00, 0.00, 0.00),
(19750.00, 24749.99, 1100.00, 2270.00, 30.00, 0.00, 0.00),
(24750.00, 29749.99, 1350.00, 2790.00, 30.00, 225.00, 475.00),
(29750.00, 34749.99, 1600.00, 3310.00, 30.00, 475.00, 1025.00),
(34750.00, NULL,     1750.00, 3630.00, 30.00, 750.00, 1550.00);

-- BIR withholding tax — monthly table (2023 onwards)
INSERT INTO tax_brackets_monthly (min_income, max_income, fixed_tax, percentage_deduction_tax) VALUES
(0.00,      20832.99,  0.00,      0.00),
(20833.00,  33332.99,  0.00,      0.15),
(33333.00,  66666.99,  1875.00,   0.20),
(66667.00,  166666.99, 8541.80,   0.25),
(166667.00, 666666.99, 33541.80,  0.30),
(666667.00, NULL,      183541.80, 0.35);

-- BIR withholding tax — semi-monthly table (2023 onwards)
INSERT INTO tax_brackets_semi_monthly (min_income, max_income, fixed_tax, percentage_deduction_tax) VALUES
(0.00,      10416.99,  0.00,     0.00),
(10417.00,  16666.99,  0.00,     0.15),
(16667.00,  33332.99,  937.50,   0.20),
(33333.00,  83332.99,  4270.70,  0.25),
(83333.00,  333332.99, 16770.70, 0.30),
(333333.00, NULL,      91770.70, 0.35);
